# Generated by Django 5.1.4 on 2024-12-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('product_creator', 'Can view and create product')]},
        ),
    ]
