# Generated by Django 5.1.4 on 2024-12-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('product_creator', 'Can view and delete product')]},
        ),
        migrations.AddField(
            model_name='product',
            name='a',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
